#!/usr/bin/env bash

export CGO_ENABLED=1
export CC=/Volumes/xtools/arm-none-linux-gnueabi/bin/arm-none-linux-gnueabi-cc
export GOARCH=arm
export GOARM=5
export GOOS=linux

go build -o build/termo-api .
